version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    ports:
      - 5432:5432
  redis:
    image: redis
    command: redis-server --requirepass frank
    ports:
      - "6379:6379"